spring:
    application:
        name: message-apps

    datasource:
        url: jdbc:mysql://localhost:3306/messaging_app
        username: root
        password: Shweta12&
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
